// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKyTucXa.Infrastructure.Persistence;

#nullable disable

namespace QuanLyKyTucXa.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuanLyKyTucXaDbContext))]
    [Migration("20260314135109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("HoaDons");

                    b.HasData(
                        new
                        {
                            MaHoaDon = 1,
                            MaHopDong = 1,
                            MaPhong = 101,
                            MaSinhVien = 1,
                            NgayThanhToan = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 1200000m,
                            TrangThai = "DaThanhToan"
                        },
                        new
                        {
                            MaHoaDon = 2,
                            MaHopDong = 2,
                            MaPhong = 103,
                            MaSinhVien = 2,
                            NgayThanhToan = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 1250000m,
                            TrangThai = "DaThanhToan"
                        },
                        new
                        {
                            MaHoaDon = 3,
                            MaHopDong = 3,
                            MaPhong = 201,
                            MaSinhVien = 3,
                            NgayThanhToan = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 1000000m,
                            TrangThai = "ChuaThanhToan"
                        });
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TienDatCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("HopDongs");

                    b.HasData(
                        new
                        {
                            MaHopDong = 1,
                            MaPhong = 101,
                            MaSinhVien = 1,
                            NgayBatDau = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TienDatCoc = 1000000m,
                            TrangThai = "HieuLuc"
                        },
                        new
                        {
                            MaHopDong = 2,
                            MaPhong = 103,
                            MaSinhVien = 2,
                            NgayBatDau = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TienDatCoc = 1000000m,
                            TrangThai = "HieuLuc"
                        },
                        new
                        {
                            MaHopDong = 3,
                            MaPhong = 201,
                            MaSinhVien = 3,
                            NgayBatDau = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TienDatCoc = 900000m,
                            TrangThai = "HieuLuc"
                        });
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            MaNhanVien = 1,
                            CCCD = "079090000001",
                            Email = "ha@kytu.com",
                            GioiTinh = "Nam",
                            HoTen = "Nguyen Hoang Ha",
                            NgaySinh = new DateTime(1990, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0912000001",
                            TrangThai = "DangLamViec"
                        },
                        new
                        {
                            MaNhanVien = 2,
                            CCCD = "079092000002",
                            Email = "lan@kytu.com",
                            GioiTinh = "Nu",
                            HoTen = "Tran Bich Lan",
                            NgaySinh = new DateTime(1992, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0912000002",
                            TrangThai = "DangLamViec"
                        });
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("MaToa")
                        .HasColumnType("int");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaToa");

                    b.HasIndex("SoPhong")
                        .IsUnique();

                    b.ToTable("Phongs");

                    b.HasData(
                        new
                        {
                            MaPhong = 101,
                            GiaPhong = 1200000m,
                            LoaiPhong = "Nam",
                            MaToa = 1,
                            SoPhong = "A101",
                            SucChua = 4,
                            TrangThai = "ConCho"
                        },
                        new
                        {
                            MaPhong = 102,
                            GiaPhong = 1200000m,
                            LoaiPhong = "Nam",
                            MaToa = 1,
                            SoPhong = "A102",
                            SucChua = 4,
                            TrangThai = "ConCho"
                        },
                        new
                        {
                            MaPhong = 103,
                            GiaPhong = 1250000m,
                            LoaiPhong = "Nu",
                            MaToa = 1,
                            SoPhong = "A103",
                            SucChua = 4,
                            TrangThai = "ConCho"
                        },
                        new
                        {
                            MaPhong = 201,
                            GiaPhong = 1000000m,
                            LoaiPhong = "Nam",
                            MaToa = 2,
                            SoPhong = "B201",
                            SucChua = 6,
                            TrangThai = "ConCho"
                        },
                        new
                        {
                            MaPhong = 202,
                            GiaPhong = 1000000m,
                            LoaiPhong = "Nu",
                            MaToa = 2,
                            SoPhong = "B202",
                            SucChua = 6,
                            TrangThai = "ConCho"
                        },
                        new
                        {
                            MaPhong = 203,
                            GiaPhong = 1000000m,
                            LoaiPhong = "Nam",
                            MaToa = 2,
                            SoPhong = "B203",
                            SucChua = 6,
                            TrangThai = "ConCho"
                        },
                        new
                        {
                            MaPhong = 204,
                            GiaPhong = 1000000m,
                            LoaiPhong = "Nu",
                            MaToa = 2,
                            SoPhong = "B204",
                            SucChua = 6,
                            TrangThai = "ConCho"
                        },
                        new
                        {
                            MaPhong = 301,
                            GiaPhong = 900000m,
                            LoaiPhong = "Nam",
                            MaToa = 3,
                            SoPhong = "C301",
                            SucChua = 8,
                            TrangThai = "ConCho"
                        },
                        new
                        {
                            MaPhong = 302,
                            GiaPhong = 900000m,
                            LoaiPhong = "Nu",
                            MaToa = 3,
                            SoPhong = "C302",
                            SucChua = 8,
                            TrangThai = "ConCho"
                        },
                        new
                        {
                            MaPhong = 303,
                            GiaPhong = 900000m,
                            LoaiPhong = "Nam",
                            MaToa = 3,
                            SoPhong = "C303",
                            SucChua = 8,
                            TrangThai = "ConCho"
                        });
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.SinhVien", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaSinhVien"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            MaSinhVien = 1,
                            CCCD = "001204000001",
                            Email = "an@kytu.com",
                            GioiTinh = "Nam",
                            HoTen = "Nguyen Van An",
                            NgaySinh = new DateTime(2004, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0901000001",
                            TrangThai = "DangO"
                        },
                        new
                        {
                            MaSinhVien = 2,
                            CCCD = "001204000002",
                            Email = "binh@kytu.com",
                            GioiTinh = "Nu",
                            HoTen = "Tran Thi Binh",
                            NgaySinh = new DateTime(2004, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0901000002",
                            TrangThai = "DangO"
                        },
                        new
                        {
                            MaSinhVien = 3,
                            CCCD = "001203000003",
                            Email = "cuong@kytu.com",
                            GioiTinh = "Nam",
                            HoTen = "Le Quang Cuong",
                            NgaySinh = new DateTime(2003, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0901000003",
                            TrangThai = "DangO"
                        },
                        new
                        {
                            MaSinhVien = 4,
                            CCCD = "001205000004",
                            Email = "duyen@kytu.com",
                            GioiTinh = "Nu",
                            HoTen = "Pham Thi Duyen",
                            NgaySinh = new DateTime(2005, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0901000004",
                            TrangThai = "DangO"
                        },
                        new
                        {
                            MaSinhVien = 5,
                            CCCD = "001204000005",
                            Email = "em@kytu.com",
                            GioiTinh = "Nam",
                            HoTen = "Vo Minh Em",
                            NgaySinh = new DateTime(2004, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0901000005",
                            TrangThai = "DangO"
                        });
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.TaiSan", b =>
                {
                    b.Property<int>("MaTaiSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaTaiSan"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayMua")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenTaiSan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaTaiSan");

                    b.HasIndex("MaPhong");

                    b.ToTable("TaiSans");

                    b.HasData(
                        new
                        {
                            MaTaiSan = 1,
                            MaPhong = 101,
                            NgayMua = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenTaiSan = "May lanh",
                            TinhTrang = "Tot"
                        },
                        new
                        {
                            MaTaiSan = 2,
                            MaPhong = 103,
                            NgayMua = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenTaiSan = "Quat tran",
                            TinhTrang = "Tot"
                        },
                        new
                        {
                            MaTaiSan = 3,
                            MaPhong = 201,
                            NgayMua = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenTaiSan = "Binh nuoc nong",
                            TinhTrang = "CanBaoTri"
                        });
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ThanhToans");

                    b.HasData(
                        new
                        {
                            MaThanhToan = 1,
                            MaHoaDon = 1,
                            NgayThanhToan = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhuongThuc = "ChuyenKhoan",
                            SoTien = 1200000m
                        },
                        new
                        {
                            MaThanhToan = 2,
                            MaHoaDon = 2,
                            NgayThanhToan = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhuongThuc = "TienMat",
                            SoTien = 1250000m
                        },
                        new
                        {
                            MaThanhToan = 3,
                            MaHoaDon = 3,
                            NgayThanhToan = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhuongThuc = "ChuyenKhoan",
                            SoTien = 1000000m
                        });
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("MaThongBao");

                    b.ToTable("ThongBaos");

                    b.HasData(
                        new
                        {
                            MaThongBao = 1,
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Sinh vien can dong tien truoc ngay 10 hang thang",
                            TieuDe = "Thong bao dong tien"
                        },
                        new
                        {
                            MaThongBao = 2,
                            NgayTao = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Kiem tra he thong dien nuoc dinh ky",
                            TieuDe = "Thong bao bao tri"
                        });
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.ToaNha", b =>
                {
                    b.Property<int>("MaToa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaToa"));

                    b.Property<int>("SoTang")
                        .HasColumnType("int");

                    b.Property<string>("TenToa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaToa");

                    b.HasIndex("TenToa")
                        .IsUnique();

                    b.ToTable("ToaNhas");

                    b.HasData(
                        new
                        {
                            MaToa = 1,
                            SoTang = 5,
                            TenToa = "Toa A"
                        },
                        new
                        {
                            MaToa = 2,
                            SoTang = 6,
                            TenToa = "Toa B"
                        },
                        new
                        {
                            MaToa = 3,
                            SoTang = 4,
                            TenToa = "Toa C"
                        });
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.YeuCauSuaChua", b =>
                {
                    b.Property<int>("MaYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaYeuCau"));

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("NgayYeuCau")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaYeuCau");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("YeuCauSuaChuas");

                    b.HasData(
                        new
                        {
                            MaYeuCau = 1,
                            MaNhanVien = 1,
                            MaSinhVien = 1,
                            MoTa = "Sua den phong A101",
                            NgayYeuCau = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "DangXuLy"
                        },
                        new
                        {
                            MaYeuCau = 2,
                            MaSinhVien = 3,
                            MoTa = "Sua quat phong B201",
                            NgayYeuCau = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "DaGui"
                        });
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.HoaDon", b =>
                {
                    b.HasOne("QuanLyKyTucXa.Domain.Entities.HopDong", null)
                        .WithMany()
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKyTucXa.Domain.Entities.Phong", null)
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKyTucXa.Domain.Entities.SinhVien", null)
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.HopDong", b =>
                {
                    b.HasOne("QuanLyKyTucXa.Domain.Entities.Phong", null)
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKyTucXa.Domain.Entities.SinhVien", null)
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.Phong", b =>
                {
                    b.HasOne("QuanLyKyTucXa.Domain.Entities.ToaNha", null)
                        .WithMany()
                        .HasForeignKey("MaToa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.TaiSan", b =>
                {
                    b.HasOne("QuanLyKyTucXa.Domain.Entities.Phong", null)
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.ThanhToan", b =>
                {
                    b.HasOne("QuanLyKyTucXa.Domain.Entities.HoaDon", null)
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyKyTucXa.Domain.Entities.YeuCauSuaChua", b =>
                {
                    b.HasOne("QuanLyKyTucXa.Domain.Entities.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyKyTucXa.Domain.Entities.SinhVien", null)
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
